# https://render.com
services:
  - type: web
    name: fittrack-pro
    runtime: node
    buildCommand: cd backend && npm install && node db/seed.js
    startCommand: cd backend && NODE_ENV=production node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_EXPIRY
        value: 15m
      - key: JWT_REFRESH_EXPIRY
        value: 7d
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: FRONTEND_URL
        sync: false
